name: Max Ryerson
favicon: null
layout_spectrum: 0.40066
typography_spectrum: 0.64005
title: 'Max Ryerson - Customer Experience & Digital Business Strategy Consultant'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-45628225-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#cae4eb'
    - '#202e35'
    - '#484d4c'
    - '#7497a0'
  brandStrength: 0.6875
  lightness: 0.7736069408711046
  saturation: 0.2451280129607767
  rhythmicContrast: 0.5
purpose: []
